// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"ceshi1/app/model/internal"
)

// Dept is the golang structure for table dept.
type Dept internal.Dept

// Fill with you ideas below.
