// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"ceshi1/app/model/internal"
)

// Permission is the golang structure for table permission.
type Permission internal.Permission

// Fill with you ideas below.

// 角色对应菜单详细信息
type PerServiceGetOne struct {
	*Permission
	Children []*Permission `json:"children"`
}
