// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"ceshi1/app/model/internal"
)

// RolePermission is the golang structure for table role_permission.
type RolePermission internal.RolePermission

// Fill with you ideas below.

// 获取角色和菜单关联信息
type RolePerGetOne struct {
	RolePermission *RolePermission
	Permission     *Permission
}
