// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"ceshi1/app/model/internal"
)

// Role is the golang structure for table role.
type Role internal.Role

// Fill with you ideas below.

// 返回角色表详细信息
type RoleServiceNameRes struct {
	Name string `json:"name"`
}
