// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"ceshi1/app/model/internal"
)

// UserRole is the golang structure for table user_role.
type UserRole internal.UserRole

// Fill with you ideas below.

// 查询用户和角色关联信息
type UserRoleGetOne struct {
	UserRole *UserRole
	Role     *Role
	// RolePerAuth []*RolePerGetOne
}

// type UserRoleAuth struct {
// 	Id   *UserRole `json:"id"`     //
// 	User *User     `json:"userId"` // user表，用户id
// 	Role *Role     `json:"roleId"` // role表，角色id
// }
