// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// Dept is the golang structure for table dept.
type Dept struct {
	DeptId     int64       `orm:"dept_id,primary" json:"deptId"`     // 部门id
	ParentId   int64       `orm:"parent_id"       json:"parentId"`   // 父部门id
	Ancestors  string      `orm:"ancestors"       json:"ancestors"`  // 祖级列表
	DeptName   string      `orm:"dept_name"       json:"deptName"`   // 部门名称
	OrderNum   int         `orm:"order_num"       json:"orderNum"`   // 显示顺序
	Leader     string      `orm:"leader"          json:"leader"`     // 负责人
	Phone      string      `orm:"phone"           json:"phone"`      // 联系电话
	Email      string      `orm:"email"           json:"email"`      // 邮箱
	Status     string      `orm:"status"          json:"status"`     // 部门状态（0正常 1停用）
	DelFlag    string      `orm:"del_flag"        json:"delFlag"`    // 删除标志（0代表存在 2代表删除）
	CreateBy   string      `orm:"create_by"       json:"createBy"`   // 创建者
	CreateTime *gtime.Time `orm:"create_time"     json:"createTime"` // 创建时间
	UpdateBy   string      `orm:"update_by"       json:"updateBy"`   // 更新者
	UpdateTime *gtime.Time `orm:"update_time"     json:"updateTime"` // 更新时间
}
