// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// RolePermission is the golang structure for table role_permission.
type RolePermission struct {
	Id           int `orm:"id,primary"    json:"id"`           //
	RoleId       int `orm:"role_id"       json:"roleId"`       // role表，角色id
	PermissionId int `orm:"permission_id" json:"permissionId"` // permission表，权限id
	CreateTime   int `orm:"create_time"   json:"createTime"`   // 创建时间
}
