// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// UserRole is the golang structure for table user_role.
type UserRole struct {
	Id         int `orm:"id,primary"  json:"id"`         //
	UserId     int `orm:"user_id"     json:"userId"`     // user表，用户id
	RoleId     int `orm:"role_id"     json:"roleId"`     // role表，角色id
	CreateTime int `orm:"create_time" json:"createTime"` // 创建时间
	UpdateTime int `orm:"update_time" json:"updateTime"` // 修改时间
	DeleteTime int `orm:"delete_time" json:"deleteTime"` // 删除时间
}
