// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// User is the golang structure for table user.
type User struct {
	Id            uint   `orm:"id,primary"      json:"id"`            //
	UserName      string `orm:"user_name"       json:"userName"`      // 用户名
	Mobile        string `orm:"mobile"          json:"mobile"`        // 手机号
	UserPassword  string `orm:"user_password"   json:"userPassword"`  // 登录密码
	CreateTime    int    `orm:"create_time"     json:"createTime"`    // 注册时间
	Sex           string `orm:"sex"             json:"sex"`           // 性别;0:保密,1:男,2:女
	Avatar        string `orm:"avatar"          json:"avatar"`        // 用户头像
	UserStatus    string `orm:"user_status"     json:"userStatus"`    // 用户状态；0:禁用,1:正常
	LastLoginTime int    `orm:"last_login_time" json:"lastLoginTime"` // 最后登录时间
	LastLoginIp   string `orm:"last_login_ip"   json:"lastLoginIp"`   // 最后登录ip
	DeptId        uint   `orm:"dept_id"         json:"deptId"`        // 部门id
	Remark        string `orm:"remark"          json:"remark"`        // 备注
	IsAdmin       string `orm:"is_admin"        json:"isAdmin"`       // 是否后台管理员；1:是，0:否
}
