// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"ceshi1/app/dao/internal"
)

// deptDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type deptDao struct {
	internal.DeptDao
}

var (
	// Dept is globally public accessible object for table dept operations.
	Dept = deptDao{
		internal.Dept,
	}
)

// Fill with you ideas below.
