// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"ceshi1/app/dao/internal"
)

// rolePermissionDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type rolePermissionDao struct {
	internal.RolePermissionDao
}

var (
	// RolePermission is globally public accessible object for table role_permission operations.
	RolePermission = rolePermissionDao{
		internal.RolePermission,
	}
)

// Fill with you ideas below.
